# Site settings
title: Leandro Carvalho
description: 'Business Card Page'
url: 'http://lrcarvalho.github.io'
baseurl: ''
profilepic: 'https://avatars.githubusercontent.com/u/46821'
bkimage: '/images/bk1.jpg'
google_analytics: 'GTM-PX82RDG'
font_awesome: 'e4ea0cab18.js'

author:
  name: 'Leandro Carvalho'
  email: contact@lrcarvalho.info
  twitter_username: lrcarvalho
#  facebook_username: joshgerdes
  github_username:  lrcarvalho
  linkedin_username:  lrcarvalho
#  meetup_name: Azure-Meetup-Rostock-MV
  cv:
    en: '/files/cv_lrcarvalho_en.pdf'
    pt_br: '/files/cv_lrcarvalho_pt.pdf'
    es: '/files/cv_lrcarvalho_es.pdf'

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
